#!/usr/bin/perl
#
# mnemonics.pl - generates mnemonic{.h,.c} from mnemonics.dat
#
# Copyright (c) 2002, 2003, 2004 Vivek Mohan <vivek@sig9.com>
# All rights reserved.
# See (LICENSE)
#
#


open(mnm_c,">mnemonics.c") || die "Couldn't create mnemonics.c.";
open(mnm_h,">mnemonics.h") || die "Couldn't create mnemonics.h.";

print mnm_c "/* Do not edit, generated by mnemonics.pl */ \n";
print mnm_c "const char* ud_mnemonics[] = { \n";

print mnm_h "/* Do not edit, generated by mnemonics.pl */ \n";
print mnm_h "#ifndef _UD_MNEMONICS_H_\n";
print mnm_h "#define _UD_MNEMONICS_H_\n";
print mnm_h "extern const char* ud_mnemonics[];\n";
print mnm_h "typedef enum ud_mnemonic_code_t { \n";

while($mnm = <STDIN>) {
	chop($mnm);
	print mnm_c "\t\"$mnm\",\n";
	print mnm_h "\tI$mnm,\n";
}

print mnm_c "\t\"I3vil\",\n";
print mnm_h "\tI3vil\n";

print mnm_c "};\n";
print mnm_h "} ud_mnemonic_code_t;\n\n";
print mnm_h "#endif\n";

close(mnm_c);
close(mnm_h);
